set_property SRC_FILE_INFO {cfile:/home/nate/Desktop/senior_design/digilent-xdc-master/Nexys-4-DDR-Master.xdc rfile:../../../../digilent-xdc-master/Nexys-4-DDR-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports a]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports y]; #IO_L18P_T2_A24_15 Sch=led[0]
